version: "3"
services:
  database:
    image: mysql
    container_name: stock_service_db
    environment:
      - MYSQL_DATABASE=stock_service_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=stock_service
      - MYSQL_PASSWORD=stock_service
      - TZ='Asia/Seoul'
    ports:
      - 3306:3306
    volumes:
      - ./db/stock_service/data:/var/lib/mysql
    networks:
      - stock_service_network
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    container_name: stock_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/stock_service_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - stock_service_network
#  redis:
#    image: redis:alpine
#    command: redis-server --port 6379
#    container_name: stock_service_redis
#    hostname: stock_service_redis
#    labels:
#      - "name=redis"
#      - "mode=standalone"
#    ports:
#      - 6379:6379

networks:
  stock_service_network: