server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    encryptKey: k1m743hyun

management:
  endpoints:
    web:
      exposure:
        exclude:
          include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    com.k1m743hyun.stockservice: DEBUG

spring:
  application:
    name: "stock"
  sql:
    init:
      mode: always
  datasource:
    url: ${STOCK_DB_URL}
    username: ${STOCK_DB_USERNAME}
    password: ${STOCK_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true